# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: failure_detector.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'failure_detector.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16\x66\x61ilure_detector.proto\x12\x10\x66\x61ilure_detector\"5\n\x0bPingRequest\x12\x11\n\tsender_id\x18\x01 \x01(\t\x12\x13\n\x0breceiver_id\x18\x02 \x01(\t\"\x1f\n\x0cPingResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x32\xa7\x01\n\x0f\x46\x61ilureDetector\x12\x45\n\x04Ping\x12\x1d.failure_detector.PingRequest\x1a\x1e.failure_detector.PingResponse\x12M\n\x0cIndirectPing\x12\x1d.failure_detector.PingRequest\x1a\x1e.failure_detector.PingResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'failure_detector_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PINGREQUEST']._serialized_start=44
  _globals['_PINGREQUEST']._serialized_end=97
  _globals['_PINGRESPONSE']._serialized_start=99
  _globals['_PINGRESPONSE']._serialized_end=130
  _globals['_FAILUREDETECTOR']._serialized_start=133
  _globals['_FAILUREDETECTOR']._serialized_end=300
# @@protoc_insertion_point(module_scope)
