# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import failure_detector_pb2 as failure__detector__pb2

GRPC_GENERATED_VERSION = '1.70.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in failure_detector_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class FailureDetectorStub(object):
    """The gRPC service for failure detection
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Ping = channel.unary_unary(
                '/failure_detector.FailureDetector/Ping',
                request_serializer=failure__detector__pb2.PingRequest.SerializeToString,
                response_deserializer=failure__detector__pb2.PingResponse.FromString,
                _registered_method=True)
        self.IndirectPing = channel.unary_unary(
                '/failure_detector.FailureDetector/IndirectPing',
                request_serializer=failure__detector__pb2.PingRequest.SerializeToString,
                response_deserializer=failure__detector__pb2.PingResponse.FromString,
                _registered_method=True)


class FailureDetectorServicer(object):
    """The gRPC service for failure detection
    """

    def Ping(self, request, context):
        """Direct ping from one node to another
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def IndirectPing(self, request, context):
        """Indirect ping when direct ping fails
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_FailureDetectorServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Ping': grpc.unary_unary_rpc_method_handler(
                    servicer.Ping,
                    request_deserializer=failure__detector__pb2.PingRequest.FromString,
                    response_serializer=failure__detector__pb2.PingResponse.SerializeToString,
            ),
            'IndirectPing': grpc.unary_unary_rpc_method_handler(
                    servicer.IndirectPing,
                    request_deserializer=failure__detector__pb2.PingRequest.FromString,
                    response_serializer=failure__detector__pb2.PingResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'failure_detector.FailureDetector', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('failure_detector.FailureDetector', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class FailureDetector(object):
    """The gRPC service for failure detection
    """

    @staticmethod
    def Ping(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/failure_detector.FailureDetector/Ping',
            failure__detector__pb2.PingRequest.SerializeToString,
            failure__detector__pb2.PingResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def IndirectPing(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/failure_detector.FailureDetector/IndirectPing',
            failure__detector__pb2.PingRequest.SerializeToString,
            failure__detector__pb2.PingResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
